import * as Yup from 'yup';

export default Yup.object().shape({
    firstname: Yup.string().required("First name is required").max(80, 'First name is too long - should be 80 chars maximum.'),
    surname: Yup.string().required("Surname is required").max(80, 'Surname is too long - should be 80 chars maximum.'),
    id_number: Yup.string().required("ID Number is required"),
    email: Yup.string().email().required("Email is required"),
    mobile_number: Yup.string().required("Mobile Number is required"),
    alternate_mobile_number: Yup.string().required("Alternate Mobile Number is required"),
    street: Yup.string().required("House or Unit Number is required"),
    street_name: Yup.string().required("Street Number is required"),
    complex_n_unit: Yup.string().required("Complex and Unit is required"),
    suburb_district: Yup.string().required("Suburb/District is required"),
    town_city: Yup.string().required("Town/City is required"),
    province: Yup.string().required("Province is required"),
    postal_code: Yup.string().required("Postal Code is required").min(4, 'Postal Code is too short').max(10, 'Postal Code is too long'),
    //payment_option: Yup.string().required("Payment Option is required"),
    //account_holder_title: Yup.string().required("Account holder title is required"),
    //account_holder_name: Yup.string().required("Account Holder Name is required"),
    //account_holder_surname: Yup.string().required("Account Holder Surname is required"),
    //bank: Yup.string().required("Bank name is required"),
    //branch: Yup.string().required("Branch Name is required"),
    //branch_code: Yup.string().required("Branch Code is required"),
    //type_of_account: Yup.string().required("Type of account is required"),
    //account_number: Yup.string().required("Account number is required"),
    method_of_communication: Yup.array().min(1,'Please choose atleast one.').of(Yup.string().trim().required()),
    race: Yup.string().required("Race is required"),
    gender: Yup.string().required("Gender is required"),
    //qualification: Yup.string().required("Qualification is required"),
    //employed: Yup.string().required("Employed is required"),
    //occupation: Yup.string().required("Occupation is required"),
    //opt_in_promotional: Yup.array().min(1,'Please choose atleast one.').of(Yup.string().trim().required()),
    how_did_you_hear_about_us: Yup.string().required("Field is required"),
    reasons_for_subscribing: Yup.string().required("Field is required"),
    referredby: Yup.string().required("Field is required"),
    referredby_firstname: Yup.string().required("Field is required"),
    referredby_surname: Yup.string().required("Field is required"),
    referral_code: Yup.string().required("Field is required"),
    referredby_email: Yup.string().email().required("Field is required"),
    referredby_mobile_number: Yup.string().required("Field is required"),
    refer_friend: Yup.string().required("Field is required"),
    //center_to_assist: Yup.string().required("Field is required"),
    //pop: Yup.string().required("Field is required"),
    //signature: Yup.string().required("Field is required"),
    //signed_place: Yup.string().required("Field is required"),
    //signed_on: Yup.string().required("Field is required")
    //password: Yup.string().required("Password is required.").min(6, 'Password is too short - should be 6 chars minimum.').max(20, 'Password is too long - should be 20 chars maximum.'),
    //confirmPassword: Yup.string().required("Confirm password is required.").oneOf([Yup.ref('password'), null], 'Password must match.'),
    //role: Yup.string().required("User Type is required")
})